# Generated by Django 4.1.6 on 2023-02-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TodosApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Task",
        ),
    ]
