# Generated by Django 4.1.6 on 2023-02-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TodosApp", "0003_task_taskcreated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="taskCreated",
        ),
    ]
